<template>
  <HeroBackground>
    <StepHeader show-brand :show-back="false">
      <nav class="flex items-center gap-3">
        <RouterLink :to="{ name: ROUTE_NAMES.LOGIN }" class="text-sm font-medium text-gray-600">로그인</RouterLink>
        <RouterLink v-slot="{ navigate }" :to="{ name: ROUTE_NAMES.SIGNUP }" custom><BaseButton size="sm" @click="navigate">시작하기</BaseButton></RouterLink>
      </nav>
    </StepHeader>

    <main ref="scrollSectionRef" class="scroll-story relative">
      <section class="kinetic-stage sticky top-0 h-[calc(100dvh-64px)] min-h-[620px] overflow-hidden" :style="stageStyle">
        <span class="ambient ambient--one" aria-hidden="true"></span><span class="ambient ambient--two" aria-hidden="true"></span>

        <Transition name="soft-fade">
          <div v-if="activeScene === 0" class="scene intro-scene">
            <p>{{ typedLine1 }}<span v-if="typingLine === 1" class="typing-cursor"></span></p>
            <p class="mt-2">{{ typedPart1 }}<span class="text-primary">{{ typedMiraero }}</span>{{ typedPart2 }}<span v-if="showDot" class="sentence-dot">.</span><span v-if="typingLine === 2" class="typing-cursor"></span></p>
          </div>
        </Transition>

        <div v-if="activeScene === 1" class="scene portal-scene">
          <p class="portal-caption" :style="portalCaptionStyle">작은 목표 하나에서</p>
          <span class="portal-dot" :style="portalStyle" aria-hidden="true"></span>
          <p class="portal-caption portal-caption--bottom" :style="portalBottomStyle">당신의 미래가 시작돼요</p>
        </div>

        <div v-if="activeScene === 2" class="scene words-scene">
          <p class="word" :style="wordStyle('goal')">목표</p><p class="word word--asset" :style="wordStyle('asset')">자산</p><p class="word word--spending" :style="wordStyle('spending')">소비</p>
          <div class="word-result" :style="wordResultStyle"><span>목표와 금융생활을</span><strong>내 현실에 맞는 계획으로</strong></div>
        </div>

        <div v-if="activeScene === 3" class="scene numbers-scene">
          <span v-for="number in floatingNumbers" :key="number.label" class="flying-number" :style="numberStyle(number)">{{ number.label }}</span>
          <div class="calculation-core" :style="calculationStyle">
            <span class="core-ring core-ring--one" aria-hidden="true"></span><span class="core-ring core-ring--two" aria-hidden="true"></span>
            <p>오늘 여유자금</p><strong>{{ calculatedAvailableMoney.toLocaleString() }}원</strong><span>오늘 지출을 빼고 남은 돈을 찾아드려요</span>
          </div>
        </div>

        <div v-if="activeScene === 4" class="scene roadmap-scene">
          <div class="roadmap-copy"><span>남은 돈은 놓치지 않게</span><strong>페이스메이커가 매일 챙겨드려요</strong></div>
          <div class="pacemaker-function">
            <Transition name="function-shift" mode="out-in">
              <div v-if="pacemakerPhase === 0" key="detect" class="function-phase">
                <p class="function-eyebrow">매일 오전 8시</p>
                <div class="detect-equation"><span><small>어제 하루 한도</small>50,000</span><b>−</b><span><small>실제 지출</small>38,000</span></div>
                <p class="function-verb">남은 돈을 찾아서</p><strong class="function-number">12,000원</strong>
              </div>
              <div v-else-if="pacemakerPhase === 1" key="save" class="function-phase">
                <p class="function-eyebrow">남은 돈 12,000원 중</p>
                <img :src="coliImage" alt="자동 저축을 돕는 페이스메이커 콜리" class="function-coli" />
                <p class="function-verb">설정한 하루 상한선 안에서</p><strong class="function-number">10,000원</strong>
                <p class="function-caption">페이스메이커 전용 저금통으로 자동 저축</p>
              </div>
              <div v-else key="connect" class="function-phase">
                <p class="function-eyebrow">매일 차곡차곡 쌓여</p>
                <p class="function-verb">이번 달 모은 금액</p><strong class="function-number function-number--total">124,000원</strong>
                <p class="function-caption">원할 때 목표 연결 자산으로 직접 입금</p>
              </div>
            </Transition>
            <ol class="function-steps" aria-label="페이스메이커 작동 단계">
              <li v-for="(step, index) in ['감지','저축','목표 연결']" :key="step" :class="{ active: pacemakerPhase === index, done: pacemakerPhase > index }"><span></span>{{ step }}</li>
            </ol>
          </div>
        </div>

        <div v-if="activeScene === 5" class="scene finale-scene">
          <div class="coach-question">“이번 달 여행 가도 돼?”</div>
          <span class="finale-halo" aria-hidden="true"></span><img :src="coliImage" alt="페이스메이커 콜리" class="finale-coli" />
          <p class="finale-kicker">AI GOAL COACH</p><h1><span>고민되는 순간마다,</span><span>콜리가 함께할게요</span></h1>
          <p class="finale-description">목표에 무리가 없는지<br />내 금융 데이터를 바탕으로 같이 계산해드려요.</p>
        </div>

        <div class="bottom-action">
          <Transition name="cta-rise" mode="out-in">
            <RouterLink v-if="activeScene === 5" v-slot="{ navigate }" :to="{ name: ROUTE_NAMES.SIGNUP }" custom><button type="button" class="primary-cta" @click="navigate">콜리와 시작하기 →</button></RouterLink>
            <button v-else type="button" class="scroll-guide" :class="{ invisible: activeScene === 0 && !typingFinished }" @click="scrollToNextScene"><span>{{ activeScene === 0 ? '스크롤해서 시작하기' : '계속 내려보기' }}</span><span aria-hidden="true">⌄</span></button>
          </Transition>
        </div>
      </section>
    </main>
  </HeroBackground>
</template>

<script setup>
import { computed, onBeforeMount, onMounted, onUnmounted, ref } from 'vue'
import { RouterLink } from 'vue-router'
import StepHeader from '@/shared/ui/StepHeader.vue'
import BaseButton from '@/shared/ui/BaseButton.vue'
import HeroBackground from '@/shared/ui/HeroBackground.vue'
import { ROUTE_NAMES } from '@/shared/constants/routes'
import coliImage from '@/assets/images/coli_bottom.png'

const scrollSectionRef = ref(null), scrollProgress = ref(0), rawScrollProgress = ref(0), typedLine1 = ref(''), typedPart1 = ref(''), typedMiraero = ref(''), typedPart2 = ref(''), typingLine = ref(0), showDot = ref(false), typingFinished = ref(false)
const timers = []
let progressFrameId = null
const floatingNumbers = [{ label:'월 수입 3,200,000',x:-118,y:-150,r:-10 },{ label:'고정지출 -920,000',x:112,y:-118,r:8 },{ label:'생활비 -1,680,000',x:-128,y:92,r:7 },{ label:'오늘 지출 -28,000',x:120,y:118,r:-8 },{ label:'목표 5,000만원',x:4,y:-205,r:4 }]
const activeScene = computed(() => scrollProgress.value < .12 ? 0 : scrollProgress.value < .28 ? 1 : scrollProgress.value < .47 ? 2 : scrollProgress.value < .66 ? 3 : scrollProgress.value < .84 ? 4 : 5)
function clamp(start,end){ return Math.min(Math.max((scrollProgress.value-start)/(end-start),0),1) }
const portalProgress=computed(()=>clamp(.12,.28)), wordsProgress=computed(()=>clamp(.28,.47)), numbersProgress=computed(()=>clamp(.47,.66)), roadmapProgress=computed(()=>clamp(.66,.84))
const stageStyle=computed(()=>({'--ambient-shift':`${scrollProgress.value*110}px`,'--ambient-opacity':String(.35+scrollProgress.value*.4)}))
const portalStyle=computed(()=>{const size=18+portalProgress.value**2*1150;return{width:`${size}px`,height:`${size}px`,opacity:String(.55+portalProgress.value*.45)}})
const portalCaptionStyle=computed(()=>({opacity:String(1-portalProgress.value*1.4),transform:`translateY(${-portalProgress.value*24}px)`}))
const portalBottomStyle=computed(()=>({opacity:String(Math.max((portalProgress.value-.55)*2.2,0)),transform:`translateY(${24-portalProgress.value*24}px)`}))
const wordResultStyle=computed(()=>{const reveal=Math.min(Math.max((wordsProgress.value-.82)/.16,0),1);return{opacity:String(reveal),transform:`translateY(${28-reveal*28}px) scale(${.96+reveal*.04})`}})
function wordStyle(type){const p=wordsProgress.value,o={goal:{x:-220,y:-190,r:-13},asset:{x:230,y:-30,r:12},spending:{x:-180,y:190,r:9}}[type],s={goal:{x:0,y:-92},asset:{x:-92,y:34},spending:{x:92,y:34}}[type],enter=Math.min(p/.34,1),exit=Math.min(Math.max((p-.62)/.18,0),1);const x=o.x+(s.x-o.x)*enter,y=o.y+(s.y-o.y)*enter-exit*80;return{opacity:String(Math.min(p*4,1)*(1-exit)),transform:`translate3d(${x}px,${y}px,0) rotate(${o.r*(1-enter)}deg) scale(${.72+enter*.28+exit*.12})`}}
function numberStyle(n){const p=numbersProgress.value,enter=Math.min(p/.22,1),gather=Math.min(Math.max((p-.28)/.3,0),1),vanish=Math.min(Math.max((p-.64)/.14,0),1);return{opacity:String(enter*(1-vanish)),transform:`translate3d(${n.x*(1-gather)}px,${n.y*(1-gather)}px,0) rotate(${n.r*(1-gather)}deg) scale(${1-gather*.42})`}}
const calculationStyle=computed(()=>{const r=Math.min(Math.max((numbersProgress.value-.78)/.18,0),1);return{opacity:String(r),transform:`scale(${.78+r*.22}) translateY(${28-r*28}px)`}})
const calculatedAvailableMoney=computed(()=>{const r=Math.min(Math.max((numbersProgress.value-.8)/.18,0),1);return Math.round((32000*r)/1000)*1000})
const pacemakerPhase=computed(()=>roadmapProgress.value<.34?0:roadmapProgress.value<.68?1:2)
function wait(ms){return new Promise(resolve=>timers.push(window.setTimeout(resolve,ms)))}
async function typeText(text,target){let value='';for(const character of text){value+=character;target.value=value;await wait(68)}}
async function runTyping(){await wait(160);typingLine.value=1;await typeText('목표만 정하면,',typedLine1);await wait(200);typingLine.value=2;await typeText('페이스는 ',typedPart1);await typeText('미래로',typedMiraero);await typeText('가 맞출게요',typedPart2);await wait(68);showDot.value=true;typingLine.value=0;typingFinished.value=true}
function animateProgress(){const difference=rawScrollProgress.value-scrollProgress.value;scrollProgress.value+=difference*.14;if(Math.abs(difference)>.0001){progressFrameId=window.requestAnimationFrame(animateProgress)}else{scrollProgress.value=rawScrollProgress.value;progressFrameId=null}}
function updateScrollProgress(){const s=scrollSectionRef.value;if(!s)return;const d=Math.max(s.offsetHeight-window.innerHeight,1);rawScrollProgress.value=Math.min(Math.max(-s.getBoundingClientRect().top/d,0),1);if(progressFrameId===null)progressFrameId=window.requestAnimationFrame(animateProgress)}
function resetToIntro(){scrollProgress.value=0;rawScrollProgress.value=0;window.scrollTo({top:0,left:0,behavior:'auto'});document.documentElement.scrollTop=0;document.body.scrollTop=0}
function scrollToNextScene(){const s=scrollSectionRef.value;if(!s)return;const targets=[0,.16,.32,.51,.7,.9],next=Math.min(activeScene.value+1,5);window.scrollTo({top:s.offsetTop+(s.offsetHeight-window.innerHeight)*targets[next],behavior:'smooth'})}
onBeforeMount(()=>{if('scrollRestoration'in window.history)window.history.scrollRestoration='manual';resetToIntro()})
onMounted(()=>{resetToIntro();window.addEventListener('scroll',updateScrollProgress,{passive:true});window.addEventListener('resize',updateScrollProgress);window.requestAnimationFrame(()=>window.requestAnimationFrame(resetToIntro));runTyping()})
onUnmounted(()=>{window.removeEventListener('scroll',updateScrollProgress);window.removeEventListener('resize',updateScrollProgress);timers.forEach(clearTimeout);if(progressFrameId!==null)window.cancelAnimationFrame(progressFrameId)})
</script>

<style scoped>
.scroll-story{display:block!important;flex:none!important;width:100%;height:900dvh!important;min-height:6000px!important;position:relative}.kinetic-stage{position:sticky;width:100%;height:calc(100dvh - 64px);min-height:0;perspective:1100px;background:rgba(248,251,255,.9)}.scene{position:absolute!important;inset:0!important;z-index:2;width:100%;height:100%;min-height:100%;display:flex;align-items:center;justify-content:center;box-sizing:border-box;padding:24px}.intro-scene{display:grid;place-content:center;justify-items:center;grid-auto-rows:max-content;text-align:center;font-size:clamp(28px,7.2vw,40px);font-weight:900;line-height:1.35;letter-spacing:-.045em;color:#111827}.intro-scene p{width:100%;text-align:center;white-space:nowrap}.typing-cursor{display:inline-block;width:.13em;height:.82em;margin-left:.08em;border-radius:2px;background:#111827;vertical-align:-.04em;animation:blink .9s steps(1) infinite}.sentence-dot{display:inline-block;width:.22em;height:.22em;margin-left:.05em;border-radius:50%;background:#0066ff;vertical-align:.08em;box-shadow:0 0 14px 4px rgba(0,102,255,.4);animation:dot-pop .45s cubic-bezier(.34,1.25,.64,1) both}.ambient{position:absolute;width:300px;height:300px;border-radius:50%;filter:blur(8px);pointer-events:none;opacity:var(--ambient-opacity)}.ambient--one{top:-120px;left:-130px;background:radial-gradient(circle,rgba(0,102,255,.24),transparent 68%);transform:translateY(var(--ambient-shift))}.ambient--two{right:-150px;bottom:-100px;background:radial-gradient(circle,rgba(16,185,129,.18),transparent 68%);transform:translateY(calc(var(--ambient-shift) * -1))}
.portal-scene{flex-direction:column;text-align:center;overflow:hidden}.portal-dot{position:absolute;border-radius:50%;background:radial-gradient(circle at 40% 35%,#2f85ff,#0066ff 60%,#0054d6);box-shadow:0 0 80px rgba(0,102,255,.35)}.portal-caption{position:relative;z-index:2;font-size:clamp(25px,7vw,38px);font-weight:900;letter-spacing:-.04em;color:#111827}.portal-caption--bottom{color:white}.words-scene,.numbers-scene{overflow:hidden}.word{position:absolute;font-size:clamp(66px,21vw,112px);font-weight:900;letter-spacing:-.08em;color:#111827;will-change:transform,opacity}.word--asset{color:#0066ff}.word--spending{color:#13a17b}.word-result{display:flex;flex-direction:column;align-items:center;gap:8px;text-align:center;color:#4b5563}.word-result strong{font-size:clamp(34px,9vw,48px);letter-spacing:-.05em;color:#111827}.flying-number{position:absolute;max-width:92vw;white-space:nowrap;font-size:clamp(15px,4.4vw,22px);font-weight:900;letter-spacing:-.04em;color:#1f2937;will-change:transform,opacity}
.calculation-core{position:relative;display:flex;width:min(330px,86vw);min-height:210px;flex-direction:column;align-items:center;justify-content:center;border:1px solid rgba(191,219,254,.9);border-radius:28px;background:rgba(255,255,255,.9);box-shadow:0 25px 70px rgba(0,102,255,.16);backdrop-filter:blur(16px)}.calculation-core p{font-size:14px;font-weight:800;color:#6b7280}.calculation-core strong{margin-top:8px;font-size:38px;letter-spacing:-.05em;color:#0066ff}.calculation-core>span:last-child{margin-top:14px;font-size:12px;color:#9ca3af}.core-ring{position:absolute;border:1px solid rgba(0,102,255,.17);border-radius:50%;animation:ring-pulse 2.4s ease-out infinite}.core-ring--one{inset:-22px}.core-ring--two{inset:-46px;animation-delay:.7s}
.roadmap-scene{flex-direction:column;padding-right:14px;padding-left:14px}.roadmap-copy{display:flex;flex-direction:column;align-items:center;gap:8px;margin-bottom:24px;text-align:center;color:#6b7280}.roadmap-copy strong{font-size:clamp(28px,7.5vw,40px);line-height:1.25;letter-spacing:-.05em;color:#111827}.elastic-card{width:100%;max-width:440px}.pace-status{display:flex;width:max-content;min-height:32px;align-items:center;margin:0 auto;padding:0 13px;border-radius:999px;background:#fff7ed;font-size:11px;font-weight:900;color:#ea580c;transition:color .4s ease,background .4s ease,transform .4s cubic-bezier(.16,1,.3,1)}.pace-status--done{background:#eff6ff;color:#0066ff;transform:scale(1.04)}.elastic-timeline{position:relative;height:250px;margin-top:14px;overflow:visible}.goal-node{position:absolute;top:8px;left:50%;z-index:5;display:flex;min-width:126px;flex-direction:column;align-items:center;padding:11px 18px;border:1px solid #bfdbfe;border-radius:20px;background:#eff6ff;box-shadow:0 10px 30px rgba(0,102,255,.13);transform:translate(-50%,var(--goal-shift));transition:transform .12s linear}.goal-node small{font-size:10px;font-weight:900;color:#60a5fa}.goal-node strong{margin-top:3px;font-size:21px;letter-spacing:-.03em;color:#0066ff;animation:date-pop .4s cubic-bezier(.16,1,.3,1)}.elastic-thread{position:absolute;top:85px;bottom:27px;left:50%;z-index:2;width:3px;border-radius:99px;background:linear-gradient(#93c5fd,#0066ff);box-shadow:0 0 14px rgba(0,102,255,.28);transform:translateX(-50%)}.thread-glow{position:absolute;top:82px;bottom:28px;left:50%;width:42px;border-radius:50%;background:rgba(0,102,255,.13);filter:blur(17px);opacity:var(--pull);transform:translateX(-50%)}.fund-chip{position:absolute;z-index:4;padding:7px 11px;border:1px solid #bbf7d0;border-radius:999px;background:rgba(240,253,244,.92);box-shadow:0 7px 20px rgba(16,185,129,.1);font-size:11px;font-weight:900;color:#059669;opacity:var(--chip-opacity);transition:transform .12s linear}.fund-chip--1{top:100px;left:5%;transform:translateX(var(--chip-shift)) rotate(-4deg)}.fund-chip--2{top:143px;right:4%;transform:translateX(var(--chip-shift-reverse)) rotate(4deg)}.fund-chip--3{top:182px;left:9%;transform:translateX(var(--chip-shift)) rotate(-3deg)}.now-node{position:absolute;bottom:3px;left:50%;z-index:5;display:flex;flex-direction:column;align-items:center;gap:6px;transform:translateX(-50%)}.now-node span{width:19px;height:19px;border:4px solid white;border-radius:50%;background:#0066ff;box-shadow:0 0 0 8px rgba(0,102,255,.11),0 4px 14px rgba(0,102,255,.26)}.now-node small{font-size:10px;font-weight:900;color:#64748b}.elastic-caption{margin-top:13px;text-align:center;font-size:13px;font-weight:800;color:#64748b}
.sentence-dot{display:inline;width:auto;height:auto;margin:0;border-radius:0;background:none;box-shadow:none;color:#111827;vertical-align:baseline;animation:period-in .2s ease-out both}.pace-aura{position:absolute;top:38px;left:50%;z-index:1;border:1px solid rgba(0,102,255,.18);border-radius:50%;pointer-events:none;opacity:var(--pull);transform:translate(-50%,-50%);animation:pace-wave 2.2s ease-out infinite}.pace-aura--one{width:150px;height:150px}.pace-aura--two{width:225px;height:225px;animation-delay:.55s}.pace-aura--three{width:310px;height:310px;animation-delay:1.1s}.goal-node--done{border-color:#60a5fa;background:#fff;box-shadow:0 0 0 9px rgba(0,102,255,.07),0 18px 48px rgba(0,102,255,.24)}.energy-particle{position:absolute;bottom:30px;left:50%;z-index:3;width:7px;height:7px;border-radius:50%;background:#60a5fa;box-shadow:0 0 12px 4px rgba(0,102,255,.4);opacity:var(--pull);animation:energy-rise 1.8s linear infinite}.energy-particle:nth-of-type(6){animation-delay:0s}.energy-particle:nth-of-type(7){animation-delay:.35s}.energy-particle:nth-of-type(8){animation-delay:.7s}.energy-particle:nth-of-type(9){animation-delay:1.05s}
.pace-status,.pace-status--done{min-height:auto;padding:0;background:transparent;box-shadow:none;transform:none}.pace-status{font-size:12px;letter-spacing:.01em;color:#f97316}.pace-status--done{color:#0066ff}.goal-node,.goal-node--done{min-width:0;padding:0;border:0;border-radius:0;background:transparent;box-shadow:none}.goal-node small{font-size:11px;letter-spacing:.08em}.goal-node strong{margin-top:4px;font-size:clamp(32px,9vw,42px);font-weight:900;letter-spacing:-.055em;text-shadow:0 8px 28px rgba(0,102,255,.2)}.fund-chip{padding:0;border:0;border-radius:0;background:transparent;box-shadow:none;font-size:clamp(14px,4vw,17px);letter-spacing:-.03em;text-shadow:0 6px 18px rgba(5,150,105,.18)}.fund-chip--1{left:4%}.fund-chip--2{right:3%}.fund-chip--3{left:8%}.elastic-caption{font-size:14px}
.morning-flow{position:relative;width:100%;max-width:440px;height:330px}.morning-time{position:absolute;top:0;left:50%;display:flex;flex-direction:column;align-items:center;color:#0066ff;transform:translateX(-50%)}.morning-time span{font-size:clamp(36px,11vw,52px);font-weight:900;line-height:1;letter-spacing:-.07em}.morning-time small{margin-top:5px;font-size:9px;font-weight:900;letter-spacing:.2em;color:#93c5fd}.morning-equation{position:absolute;top:74px;right:0;left:0;display:grid;grid-template-columns:minmax(0,1fr) 16px minmax(0,1fr) 16px minmax(0,1.18fr);align-items:end;gap:3px;text-align:center;opacity:var(--equation-fade);transform:translateY(var(--equation-y)) scale(var(--equation-scale));transition:opacity .12s linear,transform .12s linear}.morning-equation span,.morning-equation strong{display:flex;min-width:0;flex-direction:column;font-size:clamp(14px,4.3vw,20px);font-weight:900;letter-spacing:-.055em;color:#111827}.morning-equation strong{color:#0066ff}.morning-equation small{margin-bottom:4px;font-size:9px;font-weight:800;letter-spacing:-.02em;color:#94a3b8}.morning-equation b{padding-bottom:1px;font-size:18px;color:#cbd5e1}.catch-trail{position:absolute;top:157px;left:50%;z-index:1;width:180px;height:3px;border-radius:99px;background:linear-gradient(90deg,transparent,#60a5fa,#0066ff);box-shadow:0 0 20px 5px rgba(0,102,255,.22);opacity:var(--morning-catch);transform:translateX(-50%) scaleX(var(--morning-catch));animation:catch-pulse 1.4s ease-in-out infinite}.morning-coli{position:absolute;top:130px;left:50%;z-index:3;width:auto;height:92px;filter:drop-shadow(0 12px 18px rgba(0,102,255,.16));will-change:transform,opacity}.daily-saving{position:absolute;top:190px;left:50%;z-index:4;display:flex;align-items:center;gap:5px;white-space:nowrap;font-size:clamp(16px,4.8vw,22px);font-weight:900;letter-spacing:-.045em;color:#059669;text-shadow:0 8px 24px rgba(5,150,105,.2);will-change:transform,opacity}.daily-saving small{font-size:10px;color:#94a3b8}.monthly-catch{position:absolute;top:145px;right:0;left:0;z-index:5;display:flex;flex-direction:column;align-items:center;text-align:center}.monthly-catch small{font-size:11px;font-weight:900;letter-spacing:.12em;color:#60a5fa}.monthly-catch strong{margin-top:3px;font-size:clamp(38px,11vw,54px);font-weight:900;line-height:1;letter-spacing:-.07em;color:#0066ff;text-shadow:0 12px 38px rgba(0,102,255,.23)}.monthly-catch span{margin-top:7px;font-size:13px;font-weight:900;color:#111827}.morning-caption{position:absolute;right:0;bottom:7px;left:0;text-align:center;font-size:13px;font-weight:700;color:#64748b}
.line-story{position:relative;width:100%;max-width:440px;height:350px}.pace-drawing{position:absolute;inset:0;width:100%;height:100%;overflow:visible}.pace-path{fill:none;stroke-linecap:round;stroke-linejoin:round;vector-effect:non-scaling-stroke}.pace-path--ghost{stroke:#dbeafe;stroke-width:2;opacity:.55}.pace-path--active{stroke:#0066ff;stroke-width:4;stroke-dasharray:1;filter:drop-shadow(0 0 7px rgba(0,102,255,.5));will-change:stroke-dashoffset}.line-clock,.line-money,.line-goal{position:absolute;left:50%;z-index:4;display:flex;flex-direction:column;align-items:center;text-align:center;will-change:transform,opacity}.line-clock{top:40px}.line-clock strong{font-size:clamp(26px,8vw,36px);font-weight:900;line-height:1;letter-spacing:-.06em;color:#0066ff}.line-clock small,.line-money small,.line-goal small{margin-top:5px;font-size:10px;font-weight:800;color:#94a3b8}.line-money{top:112px}.line-money small{order:0;margin:0}.line-money strong{margin-top:2px;font-size:clamp(28px,8vw,38px);font-weight:900;letter-spacing:-.055em;color:#0066ff;text-shadow:0 10px 30px rgba(0,102,255,.2)}.line-coli{position:absolute;top:137px;left:50%;z-index:5;width:auto;height:92px;filter:drop-shadow(0 12px 22px rgba(0,102,255,.2));will-change:transform,opacity}.line-saving{position:absolute;z-index:4;font-size:clamp(14px,4vw,18px);font-weight:900;letter-spacing:-.04em;color:#059669;text-shadow:0 8px 22px rgba(5,150,105,.2);will-change:transform,opacity}.line-saving--1{top:235px;left:10%}.line-saving--2{top:262px;left:44%}.line-saving--3{top:238px;right:4%}.line-goal{top:224px}.line-goal small{margin:0;letter-spacing:.08em;color:#60a5fa}.line-goal strong{margin-top:4px;font-size:clamp(37px,11vw,52px);font-weight:900;line-height:1;letter-spacing:-.07em;color:#0066ff;text-shadow:0 12px 38px rgba(0,102,255,.24)}.line-goal span{margin-top:8px;font-size:12px;font-weight:800;color:#64748b}
.pacemaker-function{position:relative;width:100%;max-width:440px;height:330px}.function-phase{position:absolute;inset:0 0 54px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.function-eyebrow{font-size:12px;font-weight:900;letter-spacing:.04em;color:#60a5fa}.detect-equation{display:flex;align-items:flex-end;justify-content:center;gap:12px;margin:25px 0 22px}.detect-equation span{display:flex;flex-direction:column;font-size:clamp(24px,7.2vw,34px);font-weight:900;letter-spacing:-.06em;color:#111827}.detect-equation small{margin-bottom:5px;font-size:9px;font-weight:800;letter-spacing:0;color:#94a3b8}.detect-equation b{padding-bottom:2px;font-size:25px;font-weight:500;color:#cbd5e1}.function-verb{font-size:15px;font-weight:800;color:#64748b}.function-number{margin-top:6px;font-size:clamp(43px,13vw,62px);font-weight:900;line-height:1;letter-spacing:-.075em;color:#0066ff;text-shadow:0 13px 38px rgba(0,102,255,.2)}.function-number--total{color:#059669;text-shadow:0 13px 38px rgba(5,150,105,.18)}.function-caption{margin-top:14px;font-size:13px;font-weight:700;color:#64748b}.function-coli{width:auto;height:78px;margin:13px 0 10px;filter:drop-shadow(0 10px 18px rgba(0,102,255,.18));animation:coli-enter .65s cubic-bezier(.16,1,.3,1) both}.function-steps{position:absolute;right:22px;bottom:4px;left:22px;display:flex;align-items:center;justify-content:space-between}.function-steps li{display:flex;flex-direction:column;align-items:center;gap:7px;min-width:58px;font-size:10px;font-weight:800;color:#cbd5e1;transition:color .35s ease}.function-steps li span{width:7px;height:7px;border-radius:50%;background:#dbeafe;transition:transform .35s ease,background .35s ease,box-shadow .35s ease}.function-steps li.active{color:#0066ff}.function-steps li.active span{background:#0066ff;box-shadow:0 0 0 7px rgba(0,102,255,.1);transform:scale(1.18)}.function-steps li.done{color:#60a5fa}.function-steps li.done span{background:#60a5fa}.function-shift-enter-active,.function-shift-leave-active{transition:opacity .38s ease,transform .48s cubic-bezier(.16,1,.3,1)}.function-shift-enter-from{opacity:0;transform:translateY(32px) scale(.94)}.function-shift-leave-to{opacity:0;transform:translateY(-24px) scale(1.04)}
.finale-scene{flex-direction:column;text-align:center}.coach-question{position:relative;z-index:3;margin-bottom:12px;padding:10px 15px;border:1px solid #e5e7eb;border-radius:18px 18px 18px 5px;background:rgba(255,255,255,.96);box-shadow:0 10px 30px rgba(15,23,42,.1);font-size:13px;font-weight:800;color:#374151;animation:coach-bubble .65s .18s cubic-bezier(.16,1,.3,1) both}.finale-halo{position:absolute;width:240px;height:240px;border-radius:50%;background:radial-gradient(circle,rgba(0,102,255,.2),transparent 68%);animation:halo 2.2s ease-in-out infinite}.finale-coli{position:relative;z-index:1;height:118px;width:auto;animation:coli-enter .8s cubic-bezier(.16,1,.3,1) both}.finale-kicker{margin-top:18px;font-size:11px;font-weight:900;letter-spacing:.14em;color:#0066ff}.finale-scene h1{margin-top:10px;font-size:clamp(30px,8vw,42px);font-weight:900;line-height:1.28;letter-spacing:-.05em;color:#111827}.finale-scene h1 span{display:block;overflow:hidden;animation:text-up .7s cubic-bezier(.16,1,.3,1) both}.finale-description{margin-top:15px;font-size:14px;line-height:1.65;color:#6b7280}.bottom-action{position:absolute;z-index:20;right:20px;bottom:max(22px,env(safe-area-inset-bottom));left:20px;margin:0 auto;max-width:430px}.primary-cta{width:100%;min-height:54px;border-radius:16px;background:#0066ff;padding:0 24px;font-size:16px;font-weight:800;color:white;box-shadow:0 14px 32px rgba(0,102,255,.26)}.scroll-guide{display:flex;width:100%;min-height:48px;flex-direction:column;align-items:center;justify-content:center;border:0;background:transparent;font-size:12px;font-weight:700;color:#6b7280}.scroll-guide span:last-child{font-size:24px;line-height:.7;animation:guide 1.7s ease-in-out infinite}.invisible{opacity:0;pointer-events:none}.soft-fade-enter-active,.soft-fade-leave-active,.cta-rise-enter-active,.cta-rise-leave-active{transition:opacity .45s ease,transform .5s cubic-bezier(.16,1,.3,1)}.soft-fade-enter-from,.soft-fade-leave-to,.cta-rise-enter-from,.cta-rise-leave-to{opacity:0;transform:translateY(14px)}
@keyframes blink{0%,50%{opacity:1}50.01%,100%{opacity:0}}@keyframes dot-pop{from{transform:scale(.35)}to{transform:scale(1)}}@keyframes period-in{from{opacity:0}to{opacity:1}}@keyframes ring-pulse{from{transform:scale(.85);opacity:.8}to{transform:scale(1.15);opacity:0}}@keyframes pace-wave{0%{opacity:0;transform:translate(-50%,-50%) scale(.72)}35%{opacity:var(--pull)}100%{opacity:0;transform:translate(-50%,-50%) scale(1.08)}}@keyframes energy-rise{0%{transform:translate(-50%,0) scale(.55);filter:blur(1px)}70%{opacity:var(--pull)}100%{transform:translate(-50%,-135px) scale(1.2);opacity:0}}@keyframes catch-pulse{0%,100%{filter:brightness(1)}50%{filter:brightness(1.45)}}@keyframes date-pop{from{opacity:0;transform:translateY(-8px) scale(.86)}to{opacity:1;transform:none}}@keyframes halo{0%,100%{transform:scale(.9);opacity:.5}50%{transform:scale(1.08);opacity:1}}@keyframes coli-enter{from{opacity:0;transform:translateY(50px) scale(.72)}70%{transform:translateY(-5px) scale(1.05)}to{opacity:1;transform:none}}@keyframes coach-bubble{from{opacity:0;transform:translateY(18px) scale(.88)}to{opacity:1;transform:none}}@keyframes text-up{from{opacity:0;transform:translateY(100%)}to{opacity:1;transform:none}}@keyframes guide{0%,100%{transform:translateY(0)}50%{transform:translateY(6px)}}
@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important}}
</style>
